<a href="https://colab.research.google.com/github/marwa-kiani17/pytorch-/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision


  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-m

In [2]:
import torch

In [3]:
x=torch.empty(1)
print(x)

tensor([1.1233e+34])


In [4]:
x=torch.empty(3)
print(x)

tensor([-2.3148e+30,  3.1735e-41, -2.3146e+30])


In [5]:
x=torch.empty(2,3)
print(x)

tensor([[-2.3153e+30,  3.1735e-41, -2.3152e+30],
        [ 3.1735e-41,  8.9683e-44,  0.0000e+00]])


In [6]:
x=torch.empty(2,2,3)
print(x)

tensor([[[-2.3150e+30,  3.1735e-41, -5.0332e+29],
         [ 3.1735e-41,  1.1210e-43,  0.0000e+00]],

        [[ 8.9683e-44,  0.0000e+00,  7.3125e+33],
         [ 3.1728e-41,  0.0000e+00,  0.0000e+00]]])


In [7]:
x=torch.rand(2,2)
print(x)

tensor([[0.0175, 0.5440],
        [0.0053, 0.2804]])


In [8]:
x=torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [9]:
x=torch.zeros(2,2)
print(x.dtype)

torch.float32


In [10]:
x=torch.zeros(2,2, dtype=torch.int)
print(x.dtype)

torch.int32


In [11]:
x=torch.zeros(2,2, dtype=torch.int)
print(x.size())

torch.Size([2, 2])


In [12]:
x=torch.tensor([[1, 2], [3, 4]])
print(x)

tensor([[1, 2],
        [3, 4]])


In [13]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.6840, 0.0244],
        [0.8674, 0.7052]])
tensor([[0.2434, 0.6790],
        [0.7668, 0.2784]])


In [14]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
z=x+y

tensor([[0.8621, 0.4159],
        [0.1368, 0.1207]])
tensor([[0.3357, 0.4193],
        [0.1086, 0.2552]])


In [15]:
print(z)

tensor([[1.1978, 0.8352],
        [0.2454, 0.3760]])


In [16]:
z=torch.add(x,y)
print(z)

tensor([[1.1978, 0.8352],
        [0.2454, 0.3760]])


In [17]:
x=torch.rand(2,2)
y=torch.rand(2,2)
y.add_(x)
print(y)

tensor([[1.0629, 1.1143],
        [0.6511, 0.4443]])


In [18]:
x=torch.rand(2,2)
y=torch.rand(2,2)
z=torch.sub(x,y)
print(z)

tensor([[-0.4436,  0.0514],
        [ 0.3547, -0.3884]])


In [19]:
x=torch.rand(2,2)
y=torch.rand(2,2)
y.mul_(x)
print(y)

tensor([[0.2223, 0.0685],
        [0.1237, 0.4566]])


In [24]:
x=torch.rand(2,2)
print(x)
print(x[:,0])

tensor([[0.9158, 0.0694],
        [0.1836, 0.2866]])
tensor([0.9158, 0.1836])


In [23]:
x=torch.rand(2,2)
print(x)
print(x[0,::])

tensor([[0.9683, 0.4880],
        [0.1680, 0.8824]])
tensor([0.9683, 0.4880])


In [27]:
x=torch.rand(1,1)
print(x)
print(x[0,0].item())

tensor([[0.8373]])
0.8373141288757324


In [28]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)

tensor([[0.2280, 0.7447, 0.1885, 0.7589],
        [0.7452, 0.2010, 0.9697, 0.9974],
        [0.7584, 0.2853, 0.9809, 0.6434],
        [0.7689, 0.8748, 0.0432, 0.5914]])
tensor([0.2280, 0.7447, 0.1885, 0.7589, 0.7452, 0.2010, 0.9697, 0.9974, 0.7584,
        0.2853, 0.9809, 0.6434, 0.7689, 0.8748, 0.0432, 0.5914])


In [29]:
import numpy as np

In [30]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [32]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [34]:
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)
a=+1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
1
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [36]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    z.to("cpu")

In [37]:
x=torch.ones(5,requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
